/// <reference types="cypress" />
import './dashboard/reports.cy'
import './dashboard/pages.cy'
import './dashboard/create_page.cy'
import './dashboard/media.cy'
import './dashboard/wordup.cy'
import './dashboard/galleries.cy'
import './dashboard/speaker.cy'
import './dashboard/category.cy'
import './dashboard/songs.cy'
import './dashboard/stories.cy'
import './login/login.cy'
import './login/widgets.cy'
import './dashboard/phrases.cy'
import './dashboard/homepage.cy'
import './dashboard/member_management.cy'
import './dashboard/manage_media.cy'
