export const CATEGORIES = 'categories'
export const CHARACTERS = 'characters'
export const DICTIONARY = 'dictionary'
export const PAGES = 'pages'
export const PARTS_OF_SPEECH = 'parts-of-speech'
export const PEOPLE = 'people'
export const MY_SITES = 'my-sites'
export const SEARCH = 'search'
export const SITES = 'sites'
export const SONGS = 'songs'
export const WIDGETS = 'widgets'
export const WORD_OF_THE_DAY = 'word-of-the-day'

// MEDIA
export const AUDIO_PATH = 'audio'
export const IMAGE_PATH = 'images'
export const VIDEO_PATH = 'videos'
