/* global CONFIGURATION_SOURCE, ENV_V1_API_URL, ENV_API_URL, ENV_AWS_CLIENT_ID, ENV_OIDC_AUTHORITY_URL, ENV_OAUTH2_REDIRECT_URL, ENV_END_SESSION_URL, SSI_V1_API_URL, SSI_API_URL, SSI_AWS_CLIENT_ID, SSI_OIDC_AUTHORITY_URL, SSI_OAUTH2_REDIRECT_URL, SSI_END_SESSION_URL */

let V1_API_URL
let API_URL
let AWS_CLIENT_ID
let OIDC_AUTHORITY_URL
let OAUTH2_REDIRECT_URL
let END_SESSION_URL

switch (CONFIGURATION_SOURCE) {
  case 'SSI':
  case 'Caddy':
    // they have been injected into the HTML
    V1_API_URL = SSI_V1_API_URL
    API_URL = SSI_API_URL
    AWS_CLIENT_ID = SSI_AWS_CLIENT_ID
    OIDC_AUTHORITY_URL = SSI_OIDC_AUTHORITY_URL
    OAUTH2_REDIRECT_URL = SSI_OAUTH2_REDIRECT_URL
    END_SESSION_URL = SSI_END_SESSION_URL
    break
  case 'Webpack':
  default:
    V1_API_URL = ENV_V1_API_URL
    API_URL = ENV_API_URL
    AWS_CLIENT_ID = ENV_AWS_CLIENT_ID
    OIDC_AUTHORITY_URL = ENV_OIDC_AUTHORITY_URL
    OAUTH2_REDIRECT_URL = ENV_OAUTH2_REDIRECT_URL
    END_SESSION_URL = ENV_END_SESSION_URL
    break
}

const GlobalConfiguration = {
  V1_API_URL,
  API_URL,
  AWS_CLIENT_ID,
  OIDC_AUTHORITY_URL,
  OAUTH2_REDIRECT_URL,
  END_SESSION_URL,
}

export default GlobalConfiguration
