name: Branch protection checks

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Checkout the current working code base
      - name: Checkout working branch
        uses: actions/checkout@v3

      # Installs the correct Node version for the project
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1
        with:
          node-version: '18.16.0'

      - name: Build frontend (includes Node package install)
        run: |
          npm ci --include=dev
          npm run build:production

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Run Sonar Analysis on Frontend
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
