name: Build Frontend

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Checkout the current working code base
      - name: Checkout working branch
        uses: actions/checkout@v4

      # Installs the correct Node version for the project
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build frontend (includes Node package install)
        run: |
          npm ci --include=dev
          npm run build:production
  run-cypress-tests:
    name: Run Cypress Test Suite
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container: cypress/browsers:node-20.11.1-chrome-123.0.6312.58-1-ff-124.0-edge-122.0.2365.92-1
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Cypress
        run: npm i cypress@13.7.1
      - name: Run tests
        run: |
          npx  cypress run --config projectId=$CYPRESS_PROJECT_ID --record --key $CYPRESS_RECORD_KEY  --env baseUrl='https://fvweb-dev.eks.firstvoices.io/',DIALECT='lilwat',CYPRESS_FV_USERNAME=${{secrets.CYPRESS_FV_USERNAME}},CYPRESS_FV_PASSWORD=${{secrets.CYPRESS_FV_PASSWORD}},CYPRESS_FV_INITIALS=${{secrets.CYPRESS_FV_INITIALS}},CYPRESS_ORIGIN=${{secrets.CYPRESS_ORIGIN}} -s "cypress/e2e/core_suite_master.cy.js"
        env:
          baseUrl: 'https://fvweb-dev.eks.firstvoices.io/'
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_FV_USERNAME: ${{ secrets.CYPRESS_FV_USERNAME }}
          CYPRESS_FV_PASSWORD: ${{ secrets.CYPRESS_FV_PASSWORD }}
          CYPRESS_FV_INITIALS: ${{ secrets.CYPRESS_FV_INITIALS }}