name: Build Frontend

on:
  pull_request:
    branches:
      - master

jobs:
  build_linux:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Checkout the current working code base
      - name: Checkout working branch
        uses: actions/checkout@v3

      # Installs the correct Node version for the project
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1
        with:
          node-version: '18.16.0'

      - name: Build frontend (includes Node package install)
        run: |
          npm ci --include=dev
          npm run build:production

        # Run Sonar Analysis on Frontend
      - name: Setup Sonar Analysis For Frontend
        uses: warchant/setup-sonar-scanner@v3

        # Run Sonar Analysis on Frontend
      - name: Sonar Analysis on Frontend
        run: sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_LOGIN }}
