name: Build Frontend

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Checkout the current working code base
      - name: Checkout working branch
        uses: actions/checkout@v3

      # Installs the correct Node version for the project
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1
        with:
          node-version: '20.11.1'

      - name: Build frontend (includes Node package install)
        run: |
          npm ci --include=dev
          npm run build:production
