name: Run Cypress Tests (dependabot)

on:
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    # if: ${{ github.actor == 'dependabot[bot]' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container: cypress/browsers:node-20.11.1-chrome-123.0.6312.58-1-ff-124.0-edge-122.0.2365.92-1
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Cypress
        run: npm i cypress@13.7.1
      - name: Cypress run
        uses: cypress-io/github-actions@v6
        with:
          spec: cypress/e2e/core_suite_master.cy.js
          install: npm ci --include=dev
          build: npm run build:production
          start: npm run startDev

      # - name: Run tests
      #   run: |
      #     npx  cypress run --env baseUrl='https://fvweb-dev.eks.firstvoices.io/',DIALECT='lilwat',CYPRESS_FV_USERNAME=${{secrets.CYPRESS_FV_USERNAME}},CYPRESS_FV_PASSWORD=${{secrets.CYPRESS_FV_PASSWORD}},CYPRESS_FV_INITIALS=${{secrets.CYPRESS_FV_INITIALS}},CYPRESS_ORIGIN=${{secrets.CYPRESS_ORIGIN}} -s "cypress/e2e/core_suite_master.cy.js"
      #   env:
      #     baseUrl: 'https://fvweb-dev.eks.firstvoices.io/'
      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #     CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      #     CYPRESS_FV_USERNAME: ${{ secrets.CYPRESS_FV_USERNAME }}
      #     CYPRESS_FV_PASSWORD: ${{ secrets.CYPRESS_FV_PASSWORD }}
      #     CYPRESS_FV_INITIALS: ${{ secrets.CYPRESS_FV_INITIALS }}
