name: Testcafe-Tests
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  test_schedule:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: checkout
        uses: actions/checkout@v3
      - name: Run TestCafe tests
        uses: DevExpress/testcafe-action@latest
        with: 
          args: "chrome:headless testcafe -s testcafe/screenshots --take-snapshot actual"
      - name: install testcafe-blink-diff
        uses: DevExpress/testcafe-blink-dff@latest
        with:
          args: "testcafe/screenshots --compare base:actual --open --threshold 0.03 testcafe"
      


